In [111]:
import pandas as pd

# reading csv files
orders = pd.read_csv("orders.csv", parse_dates = ["order_date"])
customers = pd.read_csv("customers.csv", parse_dates = ["signup_date"])
products = pd.read_csv("products.csv")

# .shape
### shows rows, columns

In [112]:
print(f'---ORDERS---\n  {orders.shape}\n---CUSTOMERS---\n  {customers.shape}\n---PRODUCTS---\n  {products.shape}')

---ORDERS---
  (12480, 9)
---CUSTOMERS---
  (1500, 5)
---PRODUCTS---
  (600, 8)

# .head(n)
### TOP n & last n Orders

In [137]:
print(f'---TOP 5 ORDERS---\n')
orders.head(5)

---TOP 5 ORDERS---

,order_id,customer_id,product_id,category,brand,price,quantity,order_date,city,revenue
0,ORD10001,CUST042,PRD017,Electronics,Boat,1299.0,1,2024-01-01,Mumbai,1299.0
1,ORD10002,CUST119,PRD221,Fashion,Levis,2199.0,1,2024-01-01,Mumbai,2199.0
2,ORD10003,CUST042,PRD088,Home & Kitchen,Milton,649.0,2,2024-01-02,Mumbai,1298.0
3,ORD10004,CUST311,PRD500,Electronics,Samsung,18999.0,1,2024-01-02,Mumbai,18999.0
4,ORD10005,CUST008,PRD156,Beauty,Lakme,399.0,3,2024-01-02,Bengaluru,1197.0

In [138]:
print(f'\n---LAST 5 ORDERS---\n')
orders.tail(5)

---LAST 5 ORDERS---

,order_id,customer_id,product_id,category,brand,price,quantity,order_date,city,revenue
12475,ORD17826,CUST1226,PRD469,Fashion,Puma,616.0,2,2024-06-30,Bengaluru,1232.0
12476,ORD17827,CUST419,PRD197,Sports,Cosco,3499.0,1,2024-06-30,Delhi,3499.0
12477,ORD17827,CUST419,PRD163,Electronics,Realme,1801.0,1,2024-06-30,Delhi,1801.0
12478,ORD17827,CUST419,PRD588,Electronics,JBL,3249.0,1,2024-06-30,Delhi,3249.0
12479,ORD17828,CUST734,PRD107,Electronics,JBL,844.0,1,2024-06-30,Chennai,844.0

# .info() 
### shows cloumns and their count and datatypes

In [114]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 12480 entries, 0 to 12479
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     12480 non-null  str
 1   customer_id  12480 non-null  str
 2   product_id   12480 non-null  str
 3   category     12480 non-null  str
 4   brand        12360 non-null  str
 5   price        12480 non-null  float64
 6   quantity     12480 non-null  int64
 7   order_date   12480 non-null  datetime64[us]
 8   city         12480 non-null  str
dtypes: datetime64[us](1), float64(1), int64(1), str(6)
memory usage: 877.6 KB

# .describe() 
### finds mean, median, standard deviation, average, etc

In [115]:
orders.describe()

              price      quantity                  order_date
count  12480.000000  12480.000000                       12480
mean    1274.489744      1.663381  2024-04-02 13:49:23.076923
min      149.000000      1.000000         2024-01-01 00:00:00
25%      440.000000      1.000000         2024-02-20 00:00:00
50%      776.000000      1.000000         2024-04-04 00:00:00
75%     1555.000000      2.000000         2024-05-16 00:00:00
max    18999.000000      8.000000         2024-06-30 00:00:00
std     1728.344159      1.144670                         NaN

# Print Multiple columns

In [132]:
orders[["order_id","city","order_date"]].head(5)

   order_id       city order_date
0  ORD10001     Mumbai 2024-01-01
1  ORD10002     Mumbai 2024-01-01
2  ORD10003     Mumbai 2024-01-02
3  ORD10004     Mumbai 2024-01-02
4  ORD10005  Bengaluru 2024-01-02

# conditions

In [131]:
print(f'---Price less then 5000---\n')
orders[orders["price"] > 5000].head(5)

---Price less then 5000---

,order_id,customer_id,product_id,category,brand,price,quantity,order_date,city,revenue
3,ORD10004,CUST311,PRD500,Electronics,Samsung,18999.0,1,2024-01-02,Mumbai,18999.0
71,ORD10044,CUST386,PRD500,Electronics,Samsung,18999.0,2,2024-01-04,Kolkata,37998.0
355,ORD10227,CUST1471,PRD441,Electronics,Sony,8613.0,1,2024-01-08,Hyderabad,8613.0
411,ORD10261,CUST1302,PRD567,Electronics,Realme,5695.0,1,2024-01-09,Bengaluru,5695.0
437,ORD10278,CUST363,PRD500,Electronics,Samsung,18999.0,1,2024-01-09,Hyderabad,18999.0

# Creating a derived column

In [118]:
orders["revenue"] = orders["price"] * orders["quantity"]
print(f'Added new column "revenue"')

orders[["order_id", "price", "quantity", "revenue"]].head(5)

Added new column "revenue"

   order_id    price  quantity  revenue
0  ORD10001   1299.0         1   1299.0
1  ORD10002   2199.0         1   2199.0
2  ORD10003    649.0         2   1298.0
3  ORD10004  18999.0         1  18999.0
4  ORD10005    399.0         3   1197.0

# multiple Conditions
### Saving conditioned data in a variable

In [119]:
filter = (orders["category"] == "Electronics") & \
          (orders["city"] == "Mumbai") & \
            (orders["revenue"] > 2000)
orders[filter][["order_id", "category", "city", "brand", "revenue"]].head()

     order_id     category    city    brand  revenue
3    ORD10004  Electronics  Mumbai  Samsung  18999.0
12   ORD10009  Electronics  Mumbai  Samsung   2013.0
44   ORD10029  Electronics  Mumbai   Realme   5403.0
152  ORD10095  Electronics  Mumbai  OnePlus   2160.0
192  ORD10120  Electronics  Mumbai  OnePlus   4071.0

# .isin()
### filtering orders from particular areas

In [120]:
metro = orders[orders["city"].isin(["Mumbai", "Delhi", "Bengaluru"])]

### printing number of orders ordered in those cities

In [121]:
print(f'{len(metro)} items ordered in the three biggest metros \n("Mumbai", "Delhi", "Bengaluru")')

7577 items ordered in the three biggest metros
("Mumbai", "Delhi", "Bengaluru")

# showing data relative to categories
### groupby(col).agg( measure,operation.,eg - "sum") or [measure].sum()

In [122]:
by_category = orders.groupby("category").agg(total_revenue=("revenue", "sum")).sort_values("total_revenue", ascending=False).reset_index()

by_category

         category  total_revenue
0     Electronics      9663403.0
1  Home & Kitchen      3496498.0
2         Fashion      3133305.0
3          Sports      3034279.0
4          Beauty      1129002.0
5           Books       771678.0

### You can aggregate several measures at once with .agg()

In [123]:
summary = orders.groupby("category").agg(total_revenue = ("revenue", "sum"),
                                         total_items = ("order_id", "count"),
                                         distinct_orders = ("order_id", "nunique"),
                                         avg_price = ("price", "mean")
                                        )
summary.sort_values("total_revenue", ascending=False)

                total_revenue  total_items  distinct_orders    avg_price
category
Electronics         9663403.0         4068             3418  1861.284415
Home & Kitchen      3496498.0         2137             1942  1249.909686
Fashion             3133305.0         2429             2202   905.526554
Sports              3034279.0         1591             1504  1558.891892
Beauty              1129002.0         1480             1385   368.279054
Books                771678.0          775              750   565.285161

### Top cities where we got highest revenue

In [124]:
top_city = orders.groupby("city").agg(total_revenue = ("revenue","sum"))

top_city.sort_values("total_revenue",ascending = False).head(3)

           total_revenue
city
Mumbai         5223311.0
Delhi          4037024.0
Bengaluru      3715412.0

# merging data from other CSVs

In [125]:
ordr_cust = orders.merge(customers, on="customer_id", how="left", suffixes=("", "_cust"))
allmerged = ordr_cust.merge(products, on="product_id", how="left", suffixes=("", "_prod"))

allmerged[["order_id", "customer_id", "product_id", "segment", "category", "rating", "revenue"]].head(5)

   order_id customer_id product_id  segment        category  rating  revenue
0  ORD10001     CUST042     PRD017  Premium     Electronics     4.2   1299.0
1  ORD10002     CUST119     PRD221  Regular         Fashion     4.2   2199.0
2  ORD10003     CUST042     PRD088  Premium  Home & Kitchen     4.4   1298.0
3  ORD10004     CUST311     PRD500  Regular     Electronics     4.3  18999.0
4  ORD10005     CUST008     PRD156  Premium          Beauty     4.1   1197.0

In [126]:
 allmerged.groupby("segment")["revenue"].agg(["sum", "mean", "count"])

                sum         mean  count
segment
Premium  10630927.0  2223.113133   4782
Regular  10295572.0  1378.255957   7470

### checking missing values

In [127]:
allmerged.isna().sum()[lambda s: s > 0]

brand      120
segment    228
dtype: int64

#### Fill categorical gaps with a sensible placeholder

In [128]:
allmerged["brand"] = allmerged["brand"].fillna("Unknown")

#### Fill a segment gap with the most common value (mode)

In [129]:
allmerged["segment"] = allmerged["segment"].fillna(allmerged["segment"].mode()[0])

In [140]:
allmerged.isna().sum().sum()

np.int64(0)

#### Fixing datatypes

In [142]:
allmerged["category"] =  allmerged["category"].astype("category")
allmerged["segment"] =  allmerged["segment"].astype("category")
allmerged["order_date"] = pd.to_datetime( allmerged["order_date"])

allmerged.info()

<class 'pandas.DataFrame'>
RangeIndex: 12480 entries, 0 to 12479
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       12480 non-null  str
 1   customer_id    12480 non-null  str
 2   product_id     12480 non-null  str
 3   category       12480 non-null  category
 4   brand          12480 non-null  str
 5   price          12480 non-null  float64
 6   quantity       12480 non-null  int64
 7   order_date     12480 non-null  datetime64[us]
 8   city           12480 non-null  str
 9   revenue        12480 non-null  float64
 10  name           12480 non-null  str
 11  signup_date    12480 non-null  datetime64[us]
 12  segment        12480 non-null  category
 13  city_cust      12480 non-null  str
 14  name_prod      12480 non-null  str
 15  category_prod  12480 non-null  str
 16  brand_prod     12480 non-null  str
 17  price_prod     12480 non-null  float64
 18  rating         12480 non-null  float64
 19  description    12480 non-null  str
 20  tags           12480 non-null  str
dtypes: category(2), datetime64[us](2), float64(4), int64(1), str(12)
memory usage: 1.8 MB